name: go-jwt-middleware
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11.x, 1.12.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        id: install-go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v1
      - name: Install Dependencies
        id: install-deps
        run: go mod download
      - name: Test
        id: test
        run: go test -v
      - name: Upload to codecov.io
        id: codecov
        if: success()
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}